# Generated by Django 3.1.5 on 2021-01-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='date_of_death',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
