# Generated by Django 3.1.6 on 2021-02-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='linguisticfield',
            name='linguistic_field',
            field=models.ManyToManyField(blank=True, db_table='researchdata_m2m_linguisticfield_linguisticfield', related_name='_linguisticfield_linguistic_field_+', to='researchdata.LinguisticField'),
        ),
        migrations.AddField(
            model_name='linguistictradition',
            name='linguistic_tradition',
            field=models.ManyToManyField(blank=True, db_table='researchdata_m2m_linguistictradition_linguistictradition', related_name='_linguistictradition_linguistic_tradition_+', to='researchdata.LinguisticTradition'),
        ),
        migrations.AddField(
            model_name='reference',
            name='authors',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='reference',
            field=models.ManyToManyField(blank=True, db_table='researchdata_m2m_reference_reference', related_name='_reference_reference_+', to='researchdata.Reference'),
        ),
        migrations.AddField(
            model_name='sanskritword',
            name='sanskrit_word',
            field=models.ManyToManyField(blank=True, db_table='researchdata_m2m_sanskritword_sanskritword', related_name='_sanskritword_sanskrit_word_+', to='researchdata.SanskritWord'),
        ),
        migrations.AddField(
            model_name='text',
            name='text',
            field=models.ManyToManyField(blank=True, db_table='researchdata_m2m_text_text', related_name='_text_text_+', to='researchdata.Text'),
        ),
        migrations.AddField(
            model_name='textpassage',
            name='text_passage',
            field=models.ManyToManyField(blank=True, db_table='researchdata_m2m_textpassage_textpassage', related_name='_textpassage_text_passage_+', to='researchdata.TextPassage'),
        ),
        migrations.AlterField(
            model_name='linguisticfield',
            name='author',
            field=models.ManyToManyField(blank=True, db_table='researchdata_m2m_author_linguisticfield', related_name='linguisticfield', to='researchdata.Author'),
        ),
        migrations.AlterField(
            model_name='linguisticnotion',
            name='author',
            field=models.ManyToManyField(blank=True, db_table='researchdata_m2m_author_linguisticnotion', related_name='linguisticnotion', to='researchdata.Author'),
        ),
        migrations.AlterField(
            model_name='linguisticnotion',
            name='linguistic_field',
            field=models.ManyToManyField(blank=True, db_table='researchdata_m2m_linguisticfield_linguisticnotion', related_name='linguisticnotion', to='researchdata.LinguisticField'),
        ),
        migrations.AlterField(
            model_name='linguisticnotion',
            name='linguistic_notion',
            field=models.ManyToManyField(blank=True, db_table='researchdata_m2m_linguisticnotion_linguisticnotion', related_name='_linguisticnotion_linguistic_notion_+', to='researchdata.LinguisticNotion'),
        ),
        migrations.AlterField(
            model_name='linguistictradition',
            name='author',
            field=models.ManyToManyField(blank=True, db_table='researchdata_m2m_author_linguistictradition', related_name='linguistictradition', to='researchdata.Author'),
        ),
        migrations.AlterField(
            model_name='linguistictradition',
            name='linguistic_field',
            field=models.ManyToManyField(blank=True, db_table='researchdata_m2m_linguisticfield_linguistictradition', related_name='linguistictradition', to='researchdata.LinguisticField'),
        ),
        migrations.AlterField(
            model_name='linguistictradition',
            name='linguistic_notion',
            field=models.ManyToManyField(blank=True, db_table='researchdata_m2m_linguisticnotion_linguistictradition', related_name='linguistictradition', to='researchdata.LinguisticNotion'),
        ),
        migrations.AlterField(
            model_name='sanskritword',
            name='author',
            field=models.ManyToManyField(blank=True, db_table='researchdata_m2m_author_sanskritword', related_name='sanskritword', to='researchdata.Author'),
        ),
        migrations.AlterField(
            model_name='sanskritword',
            name='linguistic_field',
            field=models.ManyToManyField(blank=True, db_table='researchdata_m2m_linguisticfield_sanskritword', related_name='sanskritword', to='researchdata.LinguisticField'),
        ),
        migrations.AlterField(
            model_name='sanskritword',
            name='linguistic_notion',
            field=models.ManyToManyField(blank=True, db_table='researchdata_m2m_linguisticnotion_sanskritword', related_name='sanskritword', to='researchdata.LinguisticNotion'),
        ),
        migrations.AlterField(
            model_name='sanskritword',
            name='linguistic_tradition',
            field=models.ManyToManyField(blank=True, db_table='researchdata_m2m_linguistictradition_sanskritword', related_name='sanskritword', to='researchdata.LinguisticTradition'),
        ),
        migrations.AlterField(
            model_name='sanskritword',
            name='reference',
            field=models.ManyToManyField(blank=True, db_table='researchdata_m2m_reference_sanskritword', related_name='sanskritword', to='researchdata.Reference'),
        ),
        migrations.AlterField(
            model_name='textpassage',
            name='author',
            field=models.ManyToManyField(blank=True, db_table='researchdata_m2m_author_textpassage', related_name='textpassage', to='researchdata.Author'),
        ),
        migrations.AlterField(
            model_name='textpassage',
            name='linguistic_field',
            field=models.ManyToManyField(blank=True, db_table='researchdata_m2m_linguisticfield_textpassage', related_name='textpassage', to='researchdata.LinguisticField'),
        ),
        migrations.AlterField(
            model_name='textpassage',
            name='linguistic_notion',
            field=models.ManyToManyField(blank=True, db_table='researchdata_m2m_linguisticnotion_textpassage', related_name='textpassage', to='researchdata.LinguisticNotion'),
        ),
        migrations.AlterField(
            model_name='textpassage',
            name='linguistic_tradition',
            field=models.ManyToManyField(blank=True, db_table='researchdata_m2m_linguistictradition_textpassage', related_name='textpassage', to='researchdata.LinguisticTradition'),
        ),
        migrations.AlterField(
            model_name='textpassage',
            name='reference',
            field=models.ManyToManyField(blank=True, db_table='researchdata_m2m_reference_textpassage', related_name='textpassage', to='researchdata.Reference'),
        ),
        migrations.AlterField(
            model_name='textpassage',
            name='sanskrit_word',
            field=models.ManyToManyField(blank=True, db_table='researchdata_m2m_sanskritword_textpassage', related_name='textpassage', to='researchdata.SanskritWord'),
        ),
    ]
