# Generated by Django 3.1.7 on 2021-03-12 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('researchdata', '0003_auto_20210307_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='meta_citation_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reference_citation_author', to=settings.AUTH_USER_MODEL, verbose_name='Author (in citation)'),
        ),
    ]
