# Generated by Django 3.2.5 on 2021-07-04 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchdata', '0003_alter_text_author_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='alternative_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
