# Generated by Django 3.2.5 on 2021-07-09 11:02

from django.db import migrations
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('researchdata', '0004_text_alternative_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': [django.db.models.functions.text.Upper('name'), django.db.models.functions.text.Upper('alternative_name'), 'id']},
        ),
        migrations.AlterModelOptions(
            name='linguisticfield',
            options={'ordering': [django.db.models.functions.text.Upper('name'), django.db.models.functions.text.Upper('description'), 'id']},
        ),
        migrations.AlterModelOptions(
            name='linguisticnotion',
            options={'ordering': [django.db.models.functions.text.Upper('name'), django.db.models.functions.text.Upper('description'), 'id']},
        ),
        migrations.AlterModelOptions(
            name='linguistictradition',
            options={'ordering': [django.db.models.functions.text.Upper('name'), django.db.models.functions.text.Upper('description'), 'id']},
        ),
        migrations.AlterModelOptions(
            name='reference',
            options={'ordering': [django.db.models.functions.text.Upper('reference_type__name'), django.db.models.functions.text.Upper('authors_list'), django.db.models.functions.text.Upper('editors'), django.db.models.functions.text.Upper('title'), 'id']},
        ),
        migrations.AlterModelOptions(
            name='sanskritword',
            options={'ordering': [django.db.models.functions.text.Upper('name'), django.db.models.functions.text.Upper('description'), 'id']},
        ),
        migrations.AlterModelOptions(
            name='text',
            options={'ordering': [django.db.models.functions.text.Upper('name'), django.db.models.functions.text.Upper('alternative_name'), 'id']},
        ),
        migrations.AlterModelOptions(
            name='textpassage',
            options={'ordering': [django.db.models.functions.text.Upper('name'), django.db.models.functions.text.Upper('description'), 'id']},
        ),
    ]
