# Generated by Django 3.1.7 on 2021-03-12 22:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('researchdata', '0004_reference_meta_citation_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='meta_citation_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='author_citation_author', to=settings.AUTH_USER_MODEL, verbose_name='Author (in citation)'),
        ),
        migrations.AddField(
            model_name='linguisticfield',
            name='meta_citation_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='linguisticfield_citation_author', to=settings.AUTH_USER_MODEL, verbose_name='Author (in citation)'),
        ),
        migrations.AddField(
            model_name='linguisticnotion',
            name='meta_citation_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='linguisticnotion_citation_author', to=settings.AUTH_USER_MODEL, verbose_name='Author (in citation)'),
        ),
        migrations.AddField(
            model_name='linguistictradition',
            name='meta_citation_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='linguistictradition_citation_author', to=settings.AUTH_USER_MODEL, verbose_name='Author (in citation)'),
        ),
        migrations.AddField(
            model_name='sanskritword',
            name='meta_citation_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sanskritword_citation_author', to=settings.AUTH_USER_MODEL, verbose_name='Author (in citation)'),
        ),
        migrations.AddField(
            model_name='text',
            name='meta_citation_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='text_citation_author', to=settings.AUTH_USER_MODEL, verbose_name='Author (in citation)'),
        ),
        migrations.AddField(
            model_name='textpassage',
            name='meta_citation_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='textpassage_citation_author', to=settings.AUTH_USER_MODEL, verbose_name='Author (in citation)'),
        ),
    ]
