# Generated by Django 3.1.7 on 2021-03-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchdata', '0005_auto_20210312_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='meta_firstpublished_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='First Published'),
        ),
        migrations.AddField(
            model_name='linguisticfield',
            name='meta_firstpublished_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='First Published'),
        ),
        migrations.AddField(
            model_name='linguisticnotion',
            name='meta_firstpublished_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='First Published'),
        ),
        migrations.AddField(
            model_name='linguistictradition',
            name='meta_firstpublished_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='First Published'),
        ),
        migrations.AddField(
            model_name='reference',
            name='meta_firstpublished_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='First Published'),
        ),
        migrations.AddField(
            model_name='sanskritword',
            name='meta_firstpublished_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='First Published'),
        ),
        migrations.AddField(
            model_name='sllinguistictraditiongroup',
            name='meta_firstpublished_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='First Published'),
        ),
        migrations.AddField(
            model_name='slreferencepublisher',
            name='meta_firstpublished_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='First Published'),
        ),
        migrations.AddField(
            model_name='slreferencetype',
            name='meta_firstpublished_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='First Published'),
        ),
        migrations.AddField(
            model_name='sltextgroup',
            name='meta_firstpublished_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='First Published'),
        ),
        migrations.AddField(
            model_name='sltexttype',
            name='meta_firstpublished_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='First Published'),
        ),
        migrations.AddField(
            model_name='text',
            name='meta_firstpublished_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='First Published'),
        ),
        migrations.AddField(
            model_name='textpassage',
            name='meta_firstpublished_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='First Published'),
        ),
    ]
